//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportWeb.Client.Resources {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPA.Production.BlazorViews.Client.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after split.
        /// </summary>
        public static string AfterSplit {
            get {
                return ResourceManager.GetString("AfterSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Information.
        /// </summary>
        public static string ComponentInformation {
            get {
                return ResourceManager.GetString("ComponentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Datasheet.
        /// </summary>
        public static string FindDatasheet {
            get {
                return ResourceManager.GetString("FindDatasheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Image.
        /// </summary>
        public static string FindImage {
            get {
                return ResourceManager.GetString("FindImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Sharepoint.
        /// </summary>
        public static string FindInSharepoint {
            get {
                return ResourceManager.GetString("FindInSharepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is approved.
        /// </summary>
        public static string IsApproved {
            get {
                return ResourceManager.GetString("IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location No.
        /// </summary>
        public static string Location_No {
            get {
                return ResourceManager.GetString("Location No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer PartNo.
        /// </summary>
        public static string ManufacturerPartNo {
            get {
                return ResourceManager.GetString("ManufacturerPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available.
        /// </summary>
        public static string NoDataIsAvailable {
            get {
                return ResourceManager.GetString("NoDataIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items.
        /// </summary>
        public static string NumberOfItems {
            get {
                return ResourceManager.GetString("NumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On hand.
        /// </summary>
        public static string OnHand {
            get {
                return ResourceManager.GetString("OnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartNo.
        /// </summary>
        public static string PartNo {
            get {
                return ResourceManager.GetString("PartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB Name.
        /// </summary>
        public static string PCBName {
            get {
                return ResourceManager.GetString("PCBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase in.
        /// </summary>
        public static string PhaseIn {
            get {
                return ResourceManager.GetString("PhaseIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase out.
        /// </summary>
        public static string PhaseOut {
            get {
                return ResourceManager.GetString("PhaseOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece Time.
        /// </summary>
        public static string PieceTime {
            get {
                return ResourceManager.GetString("PieceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production App.
        /// </summary>
        public static string ProductionApp {
            get {
                return ResourceManager.GetString("ProductionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSV Original BOM.
        /// </summary>
        public static string SaveCsvOriginalBom {
            get {
                return ResourceManager.GetString("SaveCsvOriginalBom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanfil Developers.
        /// </summary>
        public static string ScanfilDevelopers {
            get {
                return ResourceManager.GetString("ScanfilDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Value.
        /// </summary>
        public static string SearchValue {
            get {
                return ResourceManager.GetString("SearchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Time.
        /// </summary>
        public static string SetupTime {
            get {
                return ResourceManager.GetString("SetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Hours.
        /// </summary>
        public static string SumOfHours {
            get {
                return ResourceManager.GetString("SumOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Quantity.
        /// </summary>
        public static string SumOfQuantity {
            get {
                return ResourceManager.GetString("SumOfQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time/art.
        /// </summary>
        public static string TimePerArt {
            get {
                return ResourceManager.GetString("TimePerArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Application.
        /// </summary>
        public static string WebApplication {
            get {
                return ResourceManager.GetString("WebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Workstation {
            get {
                return ResourceManager.GetString("Workstation", resourceCulture);
            }
        }
    }
}
